### PR TITLE
Full refactoring

### PR DESCRIPTION
**Pull request by dx3mod**
Completely redesigned project.

- `Connection` module implements NATS protocol communication
- Class `client` is API for users 
- Add more documentation 

Other
- Rename the project to `nats-client`
- Remove bloat Makefile and force use `test` component

### CODE REVIEW

**Comment by romanchechyotkin** [comment]
nice job, can i make some comments to get more info? wanna learn this code

**Comment by dx3mod** [comment]
Yes, of course.

**Comment by dx3mod** [comment]
I'll add comments and documentation to the code.

**Comment by dx3mod** [comment]
For now, that's all I wanted to do.

**Pull request merged**
