### PR TITLE
listener

### PR DESCRIPTION
**Pull request by romanchechyotkin**

### CODE REVIEW

**Comment by romanchechyotkin** [comment]
Hello @dx3mod, how to manage async listener properly, my code app does not receive incoming messages

**Comment by romanchechyotkin** [comment]
the current version gets OK+ messaeges as acks after requests
image
but when i want to do async listener and dont manage replies right after requests, i can see nothing 
image

**Comment by dx3mod** [comment]
I don't even know. :eyes:  Can you describe your development environment settings in the README so I can run it myself, please? I have no experience with NATS and have never done anything like this. This solution looks like a big side effect, which is not a good.

**Comment by romanchechyotkin** [comment]
run `docker run -p 4222:4222 -p 8222:8222 -p 6222:6222 --name nats-server -ti nats:latest` to run NATS
then in root dir `make test` on main ranch
on `main` brach you will see messages, but not on branch `listener`

**Comment by romanchechyotkin** [comment]
https://docs.nats.io/running-a-nats-service/nats_docker/nats-docker-tutorial
tutorial for running NATS and verifing if it's running

**Comment by dx3mod** [comment]
I got it to work this way...

```diff
@@ -47,13 +47,13 @@ module Client = struct
     in
     Lwt.return ()

-  let rec listen_messages client =
+  let handle_response client =
     let buffer = Bytes.create 1024 in
     let* num_bytes = Lwt_unix.recv client.socket buffer 0 1024 [] in
     if num_bytes > 0 then (
       let message = Bytes.sub_string buffer 0 num_bytes in
       print_endline ("GOT RESPONSE: " ^ message);
-      listen_messages client)
+      Lwt.return_unit)
     else Lwt.return ()

   let connect ?(host = default_host) ?(port = default_port) () =
@@ -68,8 +68,6 @@ module Client = struct
     let* () = Lwt_unix.connect socket_fd server_socket_address in
     let client = { sockaddr = server_socket_address; socket = socket_fd } in

-    Lwt.async (fun () -> listen_messages client);
-
     let* () = init_connect client in
     Lwt.return client

@@ -86,12 +84,14 @@ module Client = struct
             crlf payload crlf
     in
     let* () = send_message client Messages.PUB msg in
+    let* () = handle_response client in
     Lwt.return ()

   let sub client ~subject =
     let sid = unique_sid () in
     let msg = Printf.sprintf "%s %s%s" subject sid crlf in
     let* () = send_message client Messages.SUB msg in
+    let* () = handle_response client in
     Lwt.return ()

   let close client =
```
изображение

**Comment by dx3mod** [comment]
It is better to replace working with a fd with working with channels. I started refactoring and redesigning the architecture.

**Pull request closed without merging**
