### PR TITLE
Fix basic of subscription routing

### PR DESCRIPTION
**Pull request by dx3mod**
Related #15. 

Not implement `reply-to` yet.

### CODE REVIEW

**Comment by romanchechyotkin** [comment]
Copy this dune-project file to run tests
```
(lang dune 3.16)

(name nats-client)

(version 0.1.2)

(generate_opam_files true)

(source
 (github romanchechyotkin/nats.ocaml))

(authors "Roman Chechyotkin" "Mikhail Lopatin <dx3mod@bk.ru>")

(maintainers "Roman Chechyotkin")

(license Apache-2.0)

(package
 (name nats-client)
 (synopsis "NATS client")
 (description "OCaml client for NATS, the cloud native messaging system")
 (depends
  (alcotest :with-test)
  (alcotest-lwt :with-test)
  (ocaml
   (> 4.14))
  (dune 
   (>= 3.6))
  (lwt (
   >= 5.7))
  (lwt_ppx (
   >= 2.1))
  (yojson (
   >= 2.2)))
 (tags (nats)))
```

**Comment by dx3mod** [comment]
I want to cry :cry: This is not a conflict.

**Comment by romanchechyotkin** [comment]
give me 1 min

**Comment by romanchechyotkin** [comment]
check #22

**Pull request closed without merging**
